name: Build TWRP for gta4lve

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # ✅ استخدم الإصدار الجديد

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip bc curl build-essential \
          gcc clang libssl-dev lzop libxml2-utils zip rsync \
          libncurses-dev openjdk-8-jdk python2

        # رابط python2 يدويًا علشان بعض السكربتات القديمة
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Setup repo
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/faksgis/twrp_device_samsung_gta4lve.git device/samsung/gta4lve

    - name: Lunch and Build
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_gta4lve-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: recovery.img
        path: ~/twrp/out/target/product/gta4lve/recovery.img
